### PR TITLE
Add option ShowDefault

### PR DESCRIPTION
**Pull request by shumkovdenis**
If option ShowDefault, then field should show without "groups" tag.

### CODE REVIEW

**Comment by mweibel** [comment]
hi @shumkovdenis 
Thanks for your contribution!

I think a feature like this makes sense, but I'm unsure about the implementation. Could you say something about your use case?
Also `ShowDefault` is not a great naming IMO. Maybe together with clarifying the use case we could find a better name.

**Comment by shumkovdenis** [comment]
In my structure, there are many fields and I would not like to, for each field, specify a tag if this field is dobutomo for all groups. And so you can add to the configuration options with which we specify that by default to show all the fields.

**Comment by mweibel** [comment]
Hi,
This conflicts now with current master. Sorry that it took me way too long to come back to you!
Anyway are you still in need of this feature?
Please add tests if you continue to do so. Also add godoc comments as well as a README update.

**Comment by masseelch** [comment]
I can provide a PR that implements this on another way, if you are willing to merge it. This can be closes than too. Its pretty old now.

**Comment by mweibel** [comment]
closing. replaced by #29

**Pull request closed without merging**
